# Generated by Django 6.0.4 on 2026-04-30 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PopLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="City Name"
                    ),
                ),
                ("is_closed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                        ],
                        max_length=10,
                    ),
                ),
                ("model_type", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=100, null=True)),
                ("details", models.TextField()),
                ("request_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("changes", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("NOC", "Network Operations Center (NOC)"),
                            ("FIELD", "Field & Fiber Engineering"),
                            ("SUPPORT", "Helpdesk & Customer Support"),
                            ("BILLING", "Billing & Accounts"),
                            ("SALES", "Sales & Marketing"),
                            ("MANAGEMENT", "Management / Admin"),
                        ],
                        default="NOC",
                        max_length=20,
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Admin Approved?"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_core.poplocation",
                    ),
                ),
            ],
        ),
    ]
