# Generated by Django 6.0.4 on 2026-04-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="My ISP Company", max_length=255),
                ),
                (
                    "short_code",
                    models.CharField(
                        default="ISP",
                        help_text="ID generation prefix (e.g., DIPL, XYZ, TATA)",
                        max_length=20,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="company_logo/"),
                ),
                (
                    "gst_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="GST Number"
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ifsc_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="IFSC Code"
                    ),
                ),
                (
                    "upi_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="UPI ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Profile / Settings",
                "verbose_name_plural": "Company Profile / Settings",
            },
        ),
    ]
