# Generated by Django 6.0.4 on 2026-05-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0002_companyprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_key",
                    models.CharField(
                        max_length=500, unique=True, verbose_name="System License Key"
                    ),
                ),
                (
                    "hardware_mac",
                    models.CharField(
                        blank=True,
                        help_text="System Hardware ID (Auto-captured)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("7 Days Trial", "7 Days Trial (Free)"),
                            ("1 Month", "1 Month"),
                            ("3 Months", "3 Months"),
                            ("6 Months", "6 Months"),
                            ("1 Year", "1 Year"),
                            ("3 Years", "3 Years"),
                            ("5 Years", "5 Years"),
                            ("Lifetime", "Lifetime"),
                        ],
                        default="7 Days Trial",
                        max_length=50,
                    ),
                ),
                ("activation_date", models.DateField(auto_now_add=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="License Status"),
                ),
            ],
            options={
                "verbose_name": "System License & Security",
                "verbose_name_plural": "System License & Security",
            },
        ),
    ]
