# Generated by Django 6.0.4 on 2026-05-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0003_systemlicense"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_version",
                    models.CharField(
                        default="1.0.0",
                        max_length=50,
                        verbose_name="Current Software Version",
                    ),
                ),
                ("last_update_check", models.DateTimeField(auto_now=True)),
                ("is_update_available", models.BooleanField(default=False)),
                (
                    "latest_version",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Latest Available Version",
                    ),
                ),
                (
                    "release_notes",
                    models.TextField(
                        blank=True,
                        help_text="Naye update mein kya features aaye hain",
                        null=True,
                    ),
                ),
                (
                    "download_url",
                    models.URLField(
                        blank=True,
                        help_text="Naye update ki .zip file ka link",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Version & Update",
                "verbose_name_plural": "System Version & Updates",
            },
        ),
    ]
