# Generated by Django 6.0.4 on 2026-07-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0004_systemversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemlicense",
            name="allowed_modules",
            field=models.JSONField(
                default=list,
                help_text="Drag & Drop me select kiye gaye modules ki list",
            ),
        ),
        migrations.AddField(
            model_name="systemversion",
            name="install_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Installed On"),
        ),
    ]
