# Generated by Django 6.0.4 on 2026-04-30 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_crm", "0001_initial"),
        ("app_provider", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DxRLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DxR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dxr_id", models.CharField(blank=True, max_length=50, unique=True)),
                (
                    "dxr_type",
                    models.CharField(
                        choices=[
                            ("Dark Fiber", "Dark Fiber"),
                            ("X-Connect", "X-Connect"),
                            ("Rack Space", "Rack Space"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "provider_circuit_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "activation_on_hold",
                    models.BooleanField(
                        default=False, verbose_name="Activation On Hold"
                    ),
                ),
                ("activation_hold_reason", models.TextField(blank=True, null=True)),
                ("po_date", models.DateField(blank=True, null=True)),
                ("install_date", models.DateField(blank=True, null=True)),
                ("billing_date", models.DateField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("termination_reason", models.TextField(blank=True, null=True)),
                ("deactivation_extension_days", models.IntegerField(default=0)),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "sub_customer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fiber_section_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fiber_start_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fiber_start_latlong",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fiber_end_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fiber_end_latlong",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fiber_tapping_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fiber_tapping_latlong",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fiber_core", models.CharField(blank=True, max_length=100, null=True)),
                ("total_fiber_length", models.FloatField(blank=True, null=True)),
                (
                    "fiber_length_unit",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("ccr_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "xconnect_fiber_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "xconnect_port_type",
                    models.CharField(
                        blank=True, default="fiber LC-LC Dual", max_length=100
                    ),
                ),
                (
                    "a_end_floor_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "a_end_mux_details",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "a_end_isp_mmr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "b_end_floor_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "b_end_mux_details",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "b_end_isp_mmr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rack_floor_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rack_space", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "rack_from_space",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("power_kva", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "a_end_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="xconnect_a_ends",
                        to="app_crm.customer",
                    ),
                ),
                (
                    "b_end_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="xconnect_b_ends",
                        to="app_crm.customer",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dxr_customers",
                        to="app_crm.customer",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_provider.provider",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_dxr.dxrlocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DxRAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="DxR files/"),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dxr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="app_dxr.dxr",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DxRComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dxr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="app_dxr.dxr",
                    ),
                ),
            ],
        ),
    ]
