# Generated by Django 6.0.4 on 2026-04-30 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_core", "0001_initial"),
        ("app_crm", "0001_initial"),
        ("app_network", "0001_initial"),
        ("app_provider", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CircuitType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Circuit Type Name"
                    ),
                ),
                ("is_closed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Circuit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "circuit_id",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("B2B", "B2B"),
                            ("B2C", "B2C"),
                            ("CORE BW", "CORE BW"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "provider_circuit_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sub_customer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bandwidth_value",
                    models.IntegerField(default=0, verbose_name="Bandwidth Value"),
                ),
                (
                    "bandwidth_unit",
                    models.CharField(
                        choices=[("Kbps", "Kbps"), ("Mbps", "Mbps"), ("Gbps", "Gbps")],
                        default="Mbps",
                        max_length=10,
                    ),
                ),
                ("po_date", models.DateField(blank=True, null=True)),
                ("install_date", models.DateField(blank=True, null=True)),
                (
                    "test_done",
                    models.BooleanField(
                        default=False, verbose_name="Test Process Done"
                    ),
                ),
                ("billing_date", models.DateField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("termination_reason", models.TextField(blank=True, null=True)),
                (
                    "customer_wan_ip",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Customer WAN IP",
                    ),
                ),
                (
                    "customer_lan_ip",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Customer LAN IP",
                    ),
                ),
                (
                    "tp_company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tp_contact_person_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tp_contact_person_no",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "tp_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tp_media",
                    models.CharField(
                        blank=True,
                        choices=[("Wireless", "Wireless"), ("Fiber", "Fiber")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "tp_billing_cycle",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Monthly", "Monthly"),
                            ("Monthly Advance", "Monthly Advance"),
                            ("Quarterly", "Quarterly"),
                            ("Quarterly Advance", "Quarterly Advance"),
                            ("Six Month", "Six Month"),
                            ("Six Month Advance", "Six Month Advance"),
                            ("Yearly", "Yearly"),
                            ("Yearly Advance", "Yearly Advance"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("tp_billing_date", models.DateField(blank=True, null=True)),
                ("sub_customer_address", models.TextField(blank=True, null=True)),
                ("tp_termination_date", models.DateField(blank=True, null=True)),
                ("tp_termination_reason", models.TextField(blank=True, null=True)),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="Fully Removed"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="circuit_attachments/%Y/%m/%d/"
                    ),
                ),
                (
                    "attachment_name",
                    models.CharField(
                        blank=True,
                        help_text="Original filename",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comments",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Store comments in JSON format",
                    ),
                ),
                (
                    "activation_on_hold",
                    models.BooleanField(
                        default=False, verbose_name="Activation On Hold"
                    ),
                ),
                ("activation_hold_reason", models.TextField(blank=True, null=True)),
                ("deactivation_extension_days", models.IntegerField(default=0)),
                (
                    "customer_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_crm.customer",
                        verbose_name="Customer Name",
                    ),
                ),
                (
                    "dipl_pop_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_core.poplocation",
                        verbose_name="DIPL POP Location",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_provider.provider",
                    ),
                ),
                (
                    "circuit_type_obj",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_circuit.circuittype",
                        verbose_name="Circuit Type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CircuitAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="Circuit files/"),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "circuit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="app_circuit.circuit",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="CircuitTenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "sub_customer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bandwidth_value", models.IntegerField(default=0)),
                ("bandwidth_unit", models.CharField(default="Mbps", max_length=10)),
                ("billing_date", models.DateField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("termination_reason", models.TextField(blank=True, null=True)),
                ("is_closed", models.BooleanField(default=False)),
                ("deactivation_extension_days", models.IntegerField(default=0)),
                (
                    "activation_on_hold",
                    models.BooleanField(
                        default=False, verbose_name="Activation On Hold"
                    ),
                ),
                ("activation_hold_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "circuit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenants",
                        to="app_circuit.circuit",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_crm.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BandwidthModification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mod_type",
                    models.CharField(
                        choices=[("Upgrade", "Upgrade"), ("Downgrade", "Downgrade")],
                        max_length=15,
                    ),
                ),
                ("old_value", models.IntegerField()),
                ("old_unit", models.CharField(max_length=10)),
                ("new_value", models.IntegerField()),
                ("new_unit", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Hold", "Hold"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=15,
                    ),
                ),
                ("hold_reason", models.TextField(blank=True, null=True)),
                ("new_telco_value", models.FloatField(blank=True, null=True)),
                (
                    "new_telco_unit",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("old_telco_value", models.FloatField(blank=True, null=True)),
                (
                    "old_telco_unit",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("telco_delta_value", models.FloatField(blank=True, null=True)),
                (
                    "telco_delta_unit",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "circuit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bandwidth_modifications",
                        to="app_circuit.circuit",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bandwidth_modifications",
                        to="app_circuit.circuittenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CircuitTermination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "end_type",
                    models.CharField(
                        choices=[("A", "Termination A"), ("B", "Termination B")],
                        max_length=1,
                    ),
                ),
                (
                    "sfp_type",
                    models.CharField(
                        choices=[
                            ("OTGB-100M", " OTGB optical SFP 100M"),
                            ("OTGB-1G", " OTGB optical SFP 1G"),
                            ("OTGB-10G", " OTGB optical SFP 10G"),
                            ("OTGB-25G", " OTGB optical SFP 25G"),
                            ("OTGB-40G", " OTGB optical SFP 40G"),
                            ("OTGB-100G", " OTGB optical SFP 100G"),
                            ("ETGB-100M", " ETGB Copper SFP 100M"),
                            ("ETGB-1G", " ETGB Copper SFP 1G"),
                            ("ETGB-10G", " ETGB Copper SFP 10G"),
                        ],
                        max_length=50,
                        verbose_name="SFP Type / Speed",
                    ),
                ),
                (
                    "telco_bandwidth_value",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Bandwidth Value",
                    ),
                ),
                (
                    "telco_bandwidth_unit",
                    models.CharField(
                        choices=[("Kbps", "Kbps"), ("Mbps", "Mbps"), ("Gbps", "Gbps")],
                        default="Mbps",
                        max_length=10,
                        verbose_name="Bandwidth Unit",
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[("L1", "L1"), ("L2", "L2")], default="L1", max_length=2
                    ),
                ),
                (
                    "port_details",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Port Details",
                    ),
                ),
                (
                    "vlan_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="VLAN ID"
                    ),
                ),
                (
                    "ra_order_no",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="RA/Order No",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_network.bts",
                        verbose_name="Location / BTS",
                    ),
                ),
                (
                    "circuit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terminations",
                        to="app_circuit.circuit",
                    ),
                ),
                (
                    "l2poi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_network.l2poi",
                        verbose_name="L2POI",
                    ),
                ),
                (
                    "provider_network",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_provider.providernetwork",
                        verbose_name="Telco Name",
                    ),
                ),
            ],
            options={
                "unique_together": {("circuit", "end_type")},
            },
        ),
        migrations.CreateModel(
            name="CircuitShifting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_sfp_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "new_telco_bandwidth_value",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "new_telco_bandwidth_unit",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "new_connection_type",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "new_port_details",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("new_vlan_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "new_ra_order_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Hold", "Hold"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=15,
                    ),
                ),
                ("hold_reason", models.TextField(blank=True, null=True)),
                ("completion_comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "circuit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shiftings",
                        to="app_circuit.circuit",
                    ),
                ),
                (
                    "new_bts",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_network.bts",
                        verbose_name="New Location/BTS",
                    ),
                ),
                (
                    "new_l2poi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_network.l2poi",
                    ),
                ),
                (
                    "new_provider_network",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_provider.providernetwork",
                    ),
                ),
                (
                    "termination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shiftings",
                        to="app_circuit.circuittermination",
                    ),
                ),
            ],
        ),
    ]
