# Generated by Django 6.0.4 on 2026-07-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_circuit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="circuit",
            name="custom_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores dynamic drag-and-drop form data",
            ),
        ),
    ]
