# Generated by Django 6.0.4 on 2026-04-30 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_crm", "0001_initial"),
        ("app_provider", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="BTS Name")),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="BTS Code"
                    ),
                ),
                ("is_closed", models.BooleanField(default=False)),
                ("address", models.TextField(verbose_name="Address")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="L2Poi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="L2POI Name")),
                (
                    "capacity",
                    models.CharField(
                        choices=[
                            ("1G", "1G"),
                            ("10G", "10G"),
                            ("25", "25G"),
                            ("40G", "40G"),
                            ("100G", "100G"),
                        ],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                ("is_closed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_crm.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "provider_network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_provider.providernetwork",
                        verbose_name="Provider Network",
                    ),
                ),
            ],
        ),
    ]
