# Generated by Django 6.0.4 on 2026-04-30 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "technical_name",
                    models.CharField(
                        max_length=150, verbose_name="Technical Person Name"
                    ),
                ),
                (
                    "technical_email",
                    models.EmailField(max_length=254, verbose_name="Technical Email"),
                ),
                (
                    "technical_phone",
                    models.CharField(max_length=15, verbose_name="Technical Phone"),
                ),
                (
                    "isp_type",
                    models.CharField(
                        choices=[
                            ("LICENCE", "LICENCE"),
                            ("CHANNEL-PARTNER", "Channel-Partner"),
                            ("CORPORATE", "Corporate"),
                        ],
                        max_length=15,
                        verbose_name="ISP Type",
                    ),
                ),
                (
                    "customer_document",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")],
                        default="NO",
                        max_length=3,
                        verbose_name="Customer Document",
                    ),
                ),
                (
                    "billing_name",
                    models.CharField(
                        max_length=150, verbose_name="Billing Person Name"
                    ),
                ),
                (
                    "billing_contact_no",
                    models.CharField(max_length=15, verbose_name="Billing Phone"),
                ),
                (
                    "billing_email",
                    models.EmailField(max_length=254, verbose_name="Billing Email"),
                ),
                (
                    "gst_no",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="GST Number"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_closed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="customer files/"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="app_crm.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
